version: '3.8'

services:
  api:
    container_name: expochat
    build: .
    working_dir: /app
    volumes:
      - .:/app  # <- Aqui ocorre a sincronização em tempo real
    ports:
      - "3000:3000"
    tty: true
